apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoriametrics
  namespace: opentelemetry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: victoriametrics
rules:
  - apiGroups: [""]
    resources: [nodes, nodes/proxy, nodes/metrics, services, endpoints, pods]
    verbs: [get, list, watch]
  - nonResourceURLs: [/metrics, /metrics/cadvisor]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: victoriametrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: victoriametrics
subjects:
  - kind: ServiceAccount
    name: victoriametrics
    namespace: opentelemetry