apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: opentelemetry
  labels:
    app: thanos-query
spec:
  selector:
    app: thanos-query
  ports:
    - name: http
      port: 9090
      targetPort: 10902
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: opentelemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: query
          image: quay.io/thanos/thanos:v0.41.0
          args:
            - query
            - --http-address=0.0.0.0:10902
            - --grpc-address=0.0.0.0:10901
            - --endpoint=thanos-receive.opentelemetry.svc.cluster.local:10901
            - --endpoint=thanos-storegateway.opentelemetry.svc.cluster.local:10901
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi